In [1]:
import numpy as np
import pandas as pd

In [2]:
# myarr=np.array([3,5,6,80],np.float64) is also valid..
# myarr=np.array([3,5,6,80],np.object) is also valid for string and objects
# like string and dicts and many more..........
myarr=np.array([3,5,6,80],np.int64)
for i in myarr:
    print(i)

3
5
6
80


In [3]:
for i in range(len(myarr)):
    print(myarr[i])
    

3
5
6
80


In [4]:
twoD=np.array([[1,2,6,5],[563,2,6,8]],np.int64)
for i in range(len(twoD)):
    for j in range(len(twoD[0])):
        print(twoD[i,j])
    print()

1
2
6
5

563
2
6
8



## Array Creation: Conversion from other Python Structures

In [5]:
listarray=np.array([[1,2,3,4],[1,21,34,49],[71,22,36,47]])

In [6]:
listarray

array([[ 1,  2,  3,  4],
       [ 1, 21, 34, 49],
       [71, 22, 36, 47]])

In [7]:
# by default it will assingn 4 bytes that is 32 bits...
listarray.dtype

dtype('int32')

In [8]:
listarray.size

12

In [9]:
listarray.shape

(3, 4)

In [10]:
np.array({14,2,8,9,3})# not efficient for integers......

array({2, 3, 8, 9, 14}, dtype=object)

## Intrinsic numpy array creation objects.....

In [11]:
# zeros=np.zeros(5)
zeros=np.zeros((2,5))
zeros
# by default its type will be float......

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace=np.linspace(0,50,11)
lspace

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [14]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [15]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [16]:
# arr.reshape(3,11,3) # 3-d matrix
arr.reshape(3,33) # 2-d matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [17]:
# Now learn about axis in numpy
# In 1-D array there is only one axis that is axis=0
# In from 2-D array to n-D array you have 0 to n-1 axes that is n-1 number of
# matrices.....
# Now in 2-D array

In [18]:
arr=np.array([[1, 2, 4, 6],
              [9,6,3, 77],
              [12,36,580,96]])

In [19]:
arr.sum(axis=1)

array([ 13,  95, 724])

In [20]:
# ata=np.empty(1)
# ata=np.append([4],axis=0)
# # ata=np.append(4)
# # ata=np.append(4)
# # ata=np.append(4)
# ata

In [21]:
table=np.array([[1,5,8],[2,7,10],[3,5,11],[1,7,11],[1,5,8],[4,6,9],[4,7,10],[2,7,10]],np.int16)
# table=np.array([[1,5,8,10],[1,5,8,10],[1,5,8,10]],np.int16)
y=np.array([["lead"],["claim"],["rebuttal"],["conclusion"],["lead"],["counter"],["counter"],["lead"]])

In [22]:
df=pd.DataFrame(table)
# grouped_df=df.groupby([0,1,2])

y=list(df.columns)
y


[0, 1, 2]

In [23]:
def indescernibility(matrix):
    df=pd.DataFrame(table)
    # this will return the list of columns     
    y=list(df.columns)
    grouped_df=df.groupby(y)
    
    
    ind_R=list(list())
    for key, item in grouped_df:
#         print(grouped_df.get_group(key), "\n",grouped_df.get_group(key).index ,"\n\n")
        lis=[]
        for i in grouped_df.get_group(key).index:
            lis.append(i)
        ind_R.append(list(lis))
    return ind_R
indescernibility(table)

[[0, 4], [3], [1, 7], [2], [5], [6]]

In [24]:
def dispensable_and_indispensable():
    pass
    
    

In [25]:
import numpy as np

class RoughSetsReducer:

    def __size(self, x):
        return (1, x.shape[0]) if x.ndim == 1 else x.shape

    '''
    Calculates indiscernibility relation
    '''
    def indisc(self, a, x):

        def codea(a, x, b):
            yy = 0
            for i in range(0, a):
                yy += x[i] * b**(a-(i+1))
            return yy

        p, q = self.__size(x)
        ap, aq = self.__size(a)
        z = [e for e in range(1, q+1)]
        tt = np.setdiff1d(z, a)
        tt_ind = np.setdiff1d(z, tt)-1
        if x.ndim == 1:
            x = x[tt_ind]
        else:
            x = x[:, tt_ind]
        y = x
        v = [codea(aq, y, 10) for i in range(0, p)] if y.ndim == 1 \
            else [codea(aq, y[i, :], 10) for i in range(0, p)]
        y = np.transpose(v)
        if y.shape[0] == 1 and len(y.shape) == 1:
            I, yy = [1], [y]
            y = np.hstack((y, I))
            b, k, l = [y], [1], [1]
        else:
            ax = 1 if y.ndim > 1 else 0
            yy = np.sort(y, axis=ax)
            I = y.argsort(axis=ax)
            y = np.hstack((yy, I))
            b, k, l = np.unique(yy, return_index=True, return_inverse=True)
        y = np.hstack((l, I))
        m = np.max(l)
        aa = np.zeros((m+1, p), dtype=int)
        for ii in range(0, m+1):
            for j in range(0, p):
                if l[j] == ii:
                    aa[ii, j] = I[j]+1
        return aa

    '''
    Calculates lower approximation set of y
    '''
    def rslower(self, y, a, T):
        z = self.indisc(a, T)
        w = []
        p, q = self.__size(z)
        for u in range(0, p):
            zz = np.setdiff1d(z[u, :], 0)
            if np.in1d(zz, y).all():
                w = np.hstack((w, zz))
        return w.astype(dtype=int)

    '''
    Calculates upper approximation set of y
    '''
    def rsupper(self, y, a, T):
        z = self.indisc(a, T)
        w = []
        p, q = self.__size(z)
        for u in range(0, p):
            zz = np.setdiff1d(z[u, :], 0)
            zzz = np.intersect1d(zz, y)
            if len(zzz) > 0:
                w = np.hstack((w, zz))
        return w.astype(dtype=int)


    def __pospq(self, p, q):
        pm, pn = self.__size(p)
        qm, qn = self.__size(q)
        num = 0
        pp, qq = [[]] * pm, [[]] * qm
        for i in range(0, pm):
            pp[i] = np.unique(p[i, :])
        for j in range(0, qm):
            qq[j] = np.unique(q[j, :])
        b = []
        for i in range(0, qm):
            for j in range(0, pm):
                if np.in1d(pp[j], qq[i]).all():
                    num += 1
                    b = np.hstack((b, pp[j]))
        bb = np.unique(b)
        if bb.size == 0:
            dd = 1
        else:
            _, dd = self.__size(bb)
        y = float(dd - 1)/pn if 0 in bb else float(dd)/pn
        b = np.setdiff1d(bb, 0)
        return y, b

    '''
    Extract core set from C to D
    '''
    def core(self, C, D):
        x = np.hstack((C, D))
        c = np.array(range(1, C.shape[1]+1))
        d = np.array([C.shape[1]+1])
        cp, cq = self.__size(c)
        q = self.indisc(d, x)
        pp = self.indisc(c, x)
        b, w = self.__pospq(pp, q)
        a, k, kk, p = ([[]] * cq for i in range(4))
        y = []
        for u in range(0, cq):
            ind = u+1
            a[u] = np.setdiff1d(c, ind)
            p[u] = self.indisc(a[u], x)
            k[u], kk[u] = self.__pospq(p[u], q)
            if k[u] != b:
                y = np.hstack((y, ind))
        return np.array(y)

    def __sgf(self, a, r, d, x):
        pr = self.indisc(r, x)
        q = self.indisc(d, x)
        b = np.hstack((r, a))
        pb = self.indisc(b, x)
        p1, _ = self.__pospq(pb, q)
        p2, _ = self.__pospq(pr, q)
        return p1 - p2

    '''
    Return the set of irreducible attributes
    '''
    def reduce(self, C, D):

        def redu2(i, re, c, d, x):
            yre = re
            re1, re2 = self.__size(re)
            q = self.indisc(d, x)
            p = self.indisc(c, x)
            pos_cd, _ = self.__pospq(p, q)
            y, j = None, None
            for qi in range(i, re2):
                re = np.setdiff1d(re, re[qi])
                red = self.indisc(re, x)
                pos_red, _ = self.__pospq(red, q)
                if np.array_equal(pos_cd, pos_red):
                    y = re
                    j = i
                    break
                else:
                    y = yre
                    j = i + 1
                    break
            return y, j

        x = np.hstack((C, D))
        c = np.array(range(1, C.shape[1]+1))
        d = np.array([C.shape[1]+1])
        y = self.core(C, D)
        q = self.indisc(d, x)
        p = self.indisc(c, x)
        pos_cd, _ = self.__pospq(p, q)
        re = y
        red = self.indisc(y, x)
        pos_red, _ = self.__pospq(red, q)
        while pos_cd != pos_red:
            cc = np.setdiff1d(c, re)
            c1, c2 = self.__size(cc)
            yy = [0] * c2
            for i in range(0, c2):
                yy[i] = self.__sgf(cc[i], re, d, x)
            cd = np.setdiff1d(c, y)
            d1, d2 = self.__size(cd)
            for i in range(d2, c2, -1):
                yy[i] = []
            ii = np.argsort(yy)
            for v1 in range(c2-1, -1, -1):
                v2 = ii[v1]
                re = np.hstack((re, cc[v2]))
                red = self.indisc(re, x)
                pos_red, _ = self.__pospq(red, q)
        re1, re2 = self.__size(re)
        core = y
        for qi in range(re2-1, -1, -1):
            if re[qi] in core:
                y = re
                break
            re = np.setdiff1d(re, re[qi])
            red = self.indisc(re, x)
            pos_red, _ = self.__pospq(red, q)
            if np.array_equal(pos_cd, pos_red):
                y = re
        y1, y2 = self.__size(y)
        j = 0
        for i in range(0, y2):
            y, j = redu2(j, y, c, d, x)
        return y

In [26]:
table=np.array([[1,5,8],[2,7,10],[3,5,11],[1,7,11],[1,5,8],[4,6,9],[4,7,10],[2,7,10]],np.int16)
# table=np.array([[1,5,8,10],[1,5,8,10],[1,5,8,10]],np.int16)
y=np.array([["lead"],["claim"],["rebuttal"],["conclusion"],["lead"],["counter"],["counter"],["lead"]])

In [136]:
# table=np.array([[1,5,8,4],[2,7,10,6],[3,5,11,11],[1,7,11,5],[1,5,8,1],[4,6,9,6],[4,7,10,1],[2,7,10,4]],np.int16)
# table_1=np.array([[1,8,4],[2,10,6],[3,11,11],[1,11,5],[1,8,1],[4,9,6],[4,10,1],[2,10,4]])


table=np.array([[1,5,3,3,8,4,4],[2,7,3,3,10,6,6],[3,5,3,3,11,11,11]],np.int16)
print(table)
print(len(table[0]))
table_1=np.array([[1,8,4],[2,10,6],[3,11,11]])
grp=np.column_stack(table)
print(grp)
temp=pd.DataFrame(grp)
# print(list(temp.columns))
temp_grp=temp.groupby(list(temp.columns))
ind_R=list(list())
for key, item in temp_grp:
#         print(grouped_df.get_group(key), "\n",grouped_df.get_group(key).index ,"\n\n")
    lis=[]
    for i in temp_grp.get_group(key).index:
        lis.append(i)
    ind_R.append(list(lis))
print()
print(ind_R)

unique_columns=[]
for i in range(len(ind_R)):
    unique_columns.append(ind_R[i][0])
    
unique_columns.sort()
print()
print("unique columns: ",unique_columns)

unique_col_table=list(list())
for i in unique_columns:
    unique_col_table.append(list(grp[i]))
unique_col_table=np.array(unique_col_table)
print("unique_col_table:",unique_col_table)

new_table=np.column_stack(unique_col_table)
print("New table:")
print(new_table)


        
repetitive_columns=list(set(list(range(len(table[0]))))-set(unique_columns))
print("repeated columns are: ", repetitive_columns)



[[ 1  5  3  3  8  4  4]
 [ 2  7  3  3 10  6  6]
 [ 3  5  3  3 11 11 11]]
7
[[ 1  2  3]
 [ 5  7  5]
 [ 3  3  3]
 [ 3  3  3]
 [ 8 10 11]
 [ 4  6 11]
 [ 4  6 11]]

[[0], [2, 3], [5, 6], [1], [4]]

unique columns:  [0, 1, 2, 4, 5]
unique_col_table: [[ 1  2  3]
 [ 5  7  5]
 [ 3  3  3]
 [ 8 10 11]
 [ 4  6 11]]
New table:
[[ 1  5  3  8  4]
 [ 2  7  3 10  6]
 [ 3  5  3 11 11]]
repeated columns are:  [3, 6]
